export const paths = {
  root: '/',
  login: '/uLogin',
  register: '/uRegister',
  forgotPassword: '/uForgotPassword',
  dashboard: '/dashboard',
  courts: '/courts',
  courtStatus: '/court-status',
  bookings: '/bookings',
  customers: '/customers',
  customerDetail: (id: string = ':id') => `/customers/${id}`,
  customerCreate: '/customers/new',
  customerEdit: (id: string = ':id') => `/customers/${id}/edit`,
  customerCourtStatus: '/customer/court-status',
  notFound: '*',
} as const;
