export const SLOT_WIDTH = 80;

export const SCHEDULER_CONFIG = {
  START_TIME: '05:00',
  END_TIME: '23:00',
  SLOT_DURATION: 60,
} as const;

export const CUSTOMER_SCHEDULER_CONFIG = {
  START_TIME: SCHEDULER_CONFIG.START_TIME,
  END_TIME: SCHEDULER_CONFIG.END_TIME,
  SLOT_DURATION: SCHEDULER_CONFIG.SLOT_DURATION,
  DEFAULT_INTERVAL_MINUTES: SCHEDULER_CONFIG.SLOT_DURATION,
  SUPPORTED_INTERVALS: [60, 30, 15] as const,
  ROW_HEIGHT: 44,
  TIME_HEADER_HEIGHT: 42,
  COURT_COL_WIDTH: 74,
  SLOT_WIDTH,
  BASE_SLOT_WIDTH: SLOT_WIDTH,
  MIN_SLOT_WIDTH: 50,
  MAX_SLOT_WIDTH: 140,
  OVERSCAN_ROWS: 5,
} as const;

export const CUSTOMER_HOTLINE = {
  PHONE_1: '028.2204.4789',
  PHONE_2: '0988.780.723',
  LABEL: 'Lưu ý: Nếu bạn cần đặt lịch cố định vui lòng liên hệ: 028.2204.4789 hoặc 0988.780.723 để được hỗ trợ',
} as const;
